# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IndividualChannelWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndividualChannelInfo(object):
    def setupUi(self, IndividualChannelInfo):
        IndividualChannelInfo.setObjectName("IndividualChannelInfo")
        IndividualChannelInfo.resize(761, 351)
        self.horizontalLayoutWidget = QtWidgets.QWidget(IndividualChannelInfo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 761, 351))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AmplitudeHistPlot = PlotWidget(self.horizontalLayoutWidget)
        self.AmplitudeHistPlot.setObjectName("AmplitudeHistPlot")
        self.horizontalLayout.addWidget(self.AmplitudeHistPlot)
        self.SpikeRatePlot = PlotWidget(self.horizontalLayoutWidget)
        self.SpikeRatePlot.setObjectName("SpikeRatePlot")
        self.horizontalLayout.addWidget(self.SpikeRatePlot)

        self.retranslateUi(IndividualChannelInfo)
        QtCore.QMetaObject.connectSlotsByName(IndividualChannelInfo)

    def retranslateUi(self, IndividualChannelInfo):
        _translate = QtCore.QCoreApplication.translate
        IndividualChannelInfo.setWindowTitle(_translate("IndividualChannelInfo", "Individual Channel Information"))
from pyqtgraph import PlotWidget
