# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IndividualChannelWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndividualChannelInfo(object):
    def setupUi(self, IndividualChannelInfo):
        IndividualChannelInfo.setObjectName("IndividualChannelInfo")
        IndividualChannelInfo.resize(820, 587)
        self.InputElectrodeNumber = QtWidgets.QTextEdit(IndividualChannelInfo)
        self.InputElectrodeNumber.setGeometry(QtCore.QRect(100, 0, 71, 31))
        self.InputElectrodeNumber.setObjectName("InputElectrodeNumber")
        self.label = QtWidgets.QLabel(IndividualChannelInfo)
        self.label.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(IndividualChannelInfo)
        self.label_2.setGeometry(QtCore.QRect(180, 0, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(IndividualChannelInfo)
        self.label_3.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.label_3.setObjectName("label_3")
        self.InputElectrodeRow = QtWidgets.QTextEdit(IndividualChannelInfo)
        self.InputElectrodeRow.setGeometry(QtCore.QRect(220, 0, 41, 31))
        self.InputElectrodeRow.setObjectName("InputElectrodeRow")
        self.InputElectrodeCol = QtWidgets.QTextEdit(IndividualChannelInfo)
        self.InputElectrodeCol.setGeometry(QtCore.QRect(300, 0, 41, 31))
        self.InputElectrodeCol.setObjectName("InputElectrodeCol")
        self.LabelElectrodeInfo = QtWidgets.QLabel(IndividualChannelInfo)
        self.LabelElectrodeInfo.setGeometry(QtCore.QRect(350, 0, 461, 31))
        self.LabelElectrodeInfo.setObjectName("LabelElectrodeInfo")
        self.widget = QtWidgets.QWidget(IndividualChannelInfo)
        self.widget.setGeometry(QtCore.QRect(11, 40, 641, 361))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.AmplitudeHistPlot = PlotWidget(self.widget)
        self.AmplitudeHistPlot.setObjectName("AmplitudeHistPlot")
        self.gridLayout.addWidget(self.AmplitudeHistPlot, 0, 0, 1, 1)
        self.ChannelTracePlot = PlotWidget(self.widget)
        self.ChannelTracePlot.setObjectName("ChannelTracePlot")
        self.gridLayout.addWidget(self.ChannelTracePlot, 0, 1, 1, 1)
        self.SpikeRateHistPlot = PlotWidget(self.widget)
        self.SpikeRateHistPlot.setObjectName("SpikeRateHistPlot")
        self.gridLayout.addWidget(self.SpikeRateHistPlot, 1, 0, 1, 1)
        self.SpikeRatePlot = PlotWidget(self.widget)
        self.SpikeRatePlot.setEnabled(True)
        self.SpikeRatePlot.setObjectName("SpikeRatePlot")
        self.gridLayout.addWidget(self.SpikeRatePlot, 1, 1, 1, 1)
        self.label.setBuddy(self.InputElectrodeNumber)
        self.label_2.setBuddy(self.InputElectrodeRow)
        self.label_3.setBuddy(self.InputElectrodeCol)

        self.retranslateUi(IndividualChannelInfo)
        QtCore.QMetaObject.connectSlotsByName(IndividualChannelInfo)

    def retranslateUi(self, IndividualChannelInfo):
        _translate = QtCore.QCoreApplication.translate
        IndividualChannelInfo.setWindowTitle(_translate("IndividualChannelInfo", "Individual Channel Information"))
        self.label.setText(_translate("IndividualChannelInfo", "Electrode No."))
        self.label_2.setText(_translate("IndividualChannelInfo", "Row"))
        self.label_3.setText(_translate("IndividualChannelInfo", "Col"))
        self.LabelElectrodeInfo.setText(_translate("IndividualChannelInfo", "Extra information"))
from pyqtgraph import PlotWidget
