# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(936, 646)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.arrayMap = PlotWidget(self.centralwidget)
        self.arrayMap.setObjectName("arrayMap")
        self.horizontalLayout_top.addWidget(self.arrayMap)
        self.traceplot_verticalLayout = QtWidgets.QVBoxLayout()
        self.traceplot_verticalLayout.setObjectName("traceplot_verticalLayout")
        self.traceplot_1 = PlotWidget(self.centralwidget)
        self.traceplot_1.setObjectName("traceplot_1")
        self.traceplot_verticalLayout.addWidget(self.traceplot_1)
        self.traceplot_2 = PlotWidget(self.centralwidget)
        self.traceplot_2.setObjectName("traceplot_2")
        self.traceplot_verticalLayout.addWidget(self.traceplot_2)
        self.traceplot_3 = PlotWidget(self.centralwidget)
        self.traceplot_3.setObjectName("traceplot_3")
        self.traceplot_verticalLayout.addWidget(self.traceplot_3)
        self.traceplot_4 = PlotWidget(self.centralwidget)
        self.traceplot_4.setObjectName("traceplot_4")
        self.traceplot_verticalLayout.addWidget(self.traceplot_4)
        self.horizontalLayout_top.addLayout(self.traceplot_verticalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.spikeRatePlot = PlotWidget(self.centralwidget)
        self.spikeRatePlot.setObjectName("spikeRatePlot")
        self.horizontalLayout_bottom.addWidget(self.spikeRatePlot)
        self.miniMapWidget = PlotWidget(self.centralwidget)
        self.miniMapWidget.setObjectName("miniMapWidget")
        self.horizontalLayout_bottom.addWidget(self.miniMapWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_bottom)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 37))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad_offline_data = QtWidgets.QMenu(self.menuFile)
        self.menuLoad_offline_data.setObjectName("menuLoad_offline_data")
        self.menuSave_as = QtWidgets.QMenu(self.menuFile)
        self.menuSave_as.setObjectName("menuSave_as")
        self.menuExport_image = QtWidgets.QMenu(self.menuFile)
        self.menuExport_image.setObjectName("menuExport_image")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuArray_Map = QtWidgets.QMenu(self.menuView)
        self.menuArray_Map.setObjectName("menuArray_Map")
        self.menuChannel_Traces = QtWidgets.QMenu(self.menuView)
        self.menuChannel_Traces.setObjectName("menuChannel_Traces")
        self.menuSpike_Rate_Plot = QtWidgets.QMenu(self.menuView)
        self.menuSpike_Rate_Plot.setObjectName("menuSpike_Rate_Plot")
        self.menuElectrode_Minimap = QtWidgets.QMenu(self.menuView)
        self.menuElectrode_Minimap.setObjectName("menuElectrode_Minimap")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuTop_left = QtWidgets.QMenu(self.menuWindow)
        self.menuTop_left.setObjectName("menuTop_left")
        self.menuTop_right = QtWidgets.QMenu(self.menuWindow)
        self.menuTop_right.setObjectName("menuTop_right")
        self.menuBottom_left = QtWidgets.QMenu(self.menuWindow)
        self.menuBottom_left.setObjectName("menuBottom_left")
        self.menuBottom_right = QtWidgets.QMenu(self.menuWindow)
        self.menuBottom_right.setObjectName("menuBottom_right")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFilter_design = QtWidgets.QMenu(self.menuSettings)
        self.menuFilter_design.setObjectName("menuFilter_design")
        mainWindow.setMenuBar(self.menubar)
        self.actionNew_session = QtWidgets.QAction(mainWindow)
        self.actionNew_session.setObjectName("actionNew_session")
        self.actionLoad_real_time_stream = QtWidgets.QAction(mainWindow)
        self.actionLoad_real_time_stream.setObjectName("actionLoad_real_time_stream")
        self.actionChange_layout = QtWidgets.QAction(mainWindow)
        self.actionChange_layout.setObjectName("actionChange_layout")
        self.actionDocumentation = QtWidgets.QAction(mainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionParameter_1 = QtWidgets.QAction(mainWindow)
        self.actionParameter_1.setObjectName("actionParameter_1")
        self.actionParameter_2 = QtWidgets.QAction(mainWindow)
        self.actionParameter_2.setObjectName("actionParameter_2")
        self.actionParameter_3 = QtWidgets.QAction(mainWindow)
        self.actionParameter_3.setObjectName("actionParameter_3")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAnalysis_parameters = QtWidgets.QAction(mainWindow)
        self.actionAnalysis_parameters.setObjectName("actionAnalysis_parameters")
        self.actionSave = QtWidgets.QAction(mainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport_to = QtWidgets.QAction(mainWindow)
        self.actionExport_to.setObjectName("actionExport_to")
        self.actionParameter_4 = QtWidgets.QAction(mainWindow)
        self.actionParameter_4.setObjectName("actionParameter_4")
        self.actionParameter_5 = QtWidgets.QAction(mainWindow)
        self.actionParameter_5.setObjectName("actionParameter_5")
        self.actionParameter_6 = QtWidgets.QAction(mainWindow)
        self.actionParameter_6.setObjectName("actionParameter_6")
        self.actionParameter_7 = QtWidgets.QAction(mainWindow)
        self.actionParameter_7.setObjectName("actionParameter_7")
        self.actionParameter = QtWidgets.QAction(mainWindow)
        self.actionParameter.setObjectName("actionParameter")
        self.actionParameter_8 = QtWidgets.QAction(mainWindow)
        self.actionParameter_8.setObjectName("actionParameter_8")
        self.actionParameter_9 = QtWidgets.QAction(mainWindow)
        self.actionParameter_9.setObjectName("actionParameter_9")
        self.actionParameter_10 = QtWidgets.QAction(mainWindow)
        self.actionParameter_10.setObjectName("actionParameter_10")
        self.actionArray_map = QtWidgets.QAction(mainWindow)
        self.actionArray_map.setObjectName("actionArray_map")
        self.actionArray_Map_2 = QtWidgets.QAction(mainWindow)
        self.actionArray_Map_2.setObjectName("actionArray_Map_2")
        self.actionArray_Map_3 = QtWidgets.QAction(mainWindow)
        self.actionArray_Map_3.setObjectName("actionArray_Map_3")
        self.actionArray_Map_4 = QtWidgets.QAction(mainWindow)
        self.actionArray_Map_4.setObjectName("actionArray_Map_4")
        self.actionChannel_Traces_2 = QtWidgets.QAction(mainWindow)
        self.actionChannel_Traces_2.setObjectName("actionChannel_Traces_2")
        self.actionChannel_Traces_3 = QtWidgets.QAction(mainWindow)
        self.actionChannel_Traces_3.setObjectName("actionChannel_Traces_3")
        self.actionChannel_Traces_4 = QtWidgets.QAction(mainWindow)
        self.actionChannel_Traces_4.setObjectName("actionChannel_Traces_4")
        self.actionSpike_Rate_Plot_2 = QtWidgets.QAction(mainWindow)
        self.actionSpike_Rate_Plot_2.setObjectName("actionSpike_Rate_Plot_2")
        self.actionElectrode_Minimap = QtWidgets.QAction(mainWindow)
        self.actionElectrode_Minimap.setObjectName("actionElectrode_Minimap")
        self.actionParameter_11 = QtWidgets.QAction(mainWindow)
        self.actionParameter_11.setObjectName("actionParameter_11")
        self.actionParameter_12 = QtWidgets.QAction(mainWindow)
        self.actionParameter_12.setObjectName("actionParameter_12")
        self.actionParameter_13 = QtWidgets.QAction(mainWindow)
        self.actionParameter_13.setObjectName("actionParameter_13")
        self.actionSpike_detection = QtWidgets.QAction(mainWindow)
        self.actionSpike_detection.setObjectName("actionSpike_detection")
        self.action_npz = QtWidgets.QAction(mainWindow)
        self.action_npz.setObjectName("action_npz")
        self.action_mat = QtWidgets.QAction(mainWindow)
        self.action_mat.setObjectName("action_mat")
        self.action_save_npz = QtWidgets.QAction(mainWindow)
        self.action_save_npz.setObjectName("action_save_npz")
        self.action_save_mat = QtWidgets.QAction(mainWindow)
        self.action_save_mat.setObjectName("action_save_mat")
        self.actionChannel_Traces = QtWidgets.QAction(mainWindow)
        self.actionChannel_Traces.setObjectName("actionChannel_Traces")
        self.actionSpike_Rate_Plot = QtWidgets.QAction(mainWindow)
        self.actionSpike_Rate_Plot.setObjectName("actionSpike_Rate_Plot")
        self.actionElectrode_Minimap_2 = QtWidgets.QAction(mainWindow)
        self.actionElectrode_Minimap_2.setObjectName("actionElectrode_Minimap_2")
        self.actionSpike_Rate_Plot_3 = QtWidgets.QAction(mainWindow)
        self.actionSpike_Rate_Plot_3.setObjectName("actionSpike_Rate_Plot_3")
        self.actionElectrode_Minimap_3 = QtWidgets.QAction(mainWindow)
        self.actionElectrode_Minimap_3.setObjectName("actionElectrode_Minimap_3")
        self.actionSpike_Rate_Plot_4 = QtWidgets.QAction(mainWindow)
        self.actionSpike_Rate_Plot_4.setObjectName("actionSpike_Rate_Plot_4")
        self.actionElectrode_Minimap_4 = QtWidgets.QAction(mainWindow)
        self.actionElectrode_Minimap_4.setObjectName("actionElectrode_Minimap_4")
        self.action_save_csv = QtWidgets.QAction(mainWindow)
        self.action_save_csv.setObjectName("action_save_csv")
        self.action_csv = QtWidgets.QAction(mainWindow)
        self.action_csv.setObjectName("action_csv")
        self.actionEntire_window = QtWidgets.QAction(mainWindow)
        self.actionEntire_window.setObjectName("actionEntire_window")
        self.actionWindow_1 = QtWidgets.QAction(mainWindow)
        self.actionWindow_1.setObjectName("actionWindow_1")
        self.actionWindow_2 = QtWidgets.QAction(mainWindow)
        self.actionWindow_2.setObjectName("actionWindow_2")
        self.actionWindow_3 = QtWidgets.QAction(mainWindow)
        self.actionWindow_3.setObjectName("actionWindow_3")
        self.actionWindow_4 = QtWidgets.QAction(mainWindow)
        self.actionWindow_4.setObjectName("actionWindow_4")
        self.actionTrace_Search = QtWidgets.QAction(mainWindow)
        self.actionTrace_Search.setObjectName("actionTrace_Search")
        self.actionTrace_Search_2 = QtWidgets.QAction(mainWindow)
        self.actionTrace_Search_2.setObjectName("actionTrace_Search_2")
        self.actionTrace_Search_3 = QtWidgets.QAction(mainWindow)
        self.actionTrace_Search_3.setObjectName("actionTrace_Search_3")
        self.actionTrace_Search_4 = QtWidgets.QAction(mainWindow)
        self.actionTrace_Search_4.setObjectName("actionTrace_Search_4")
        self.actionToggle_light_dark_mode = QtWidgets.QAction(mainWindow)
        self.actionToggle_light_dark_mode.setObjectName("actionToggle_light_dark_mode")
        self.actionToggle_profiling = QtWidgets.QAction(mainWindow)
        self.actionToggle_profiling.setObjectName("actionToggle_profiling")
        self.actionH0_Bandpass = QtWidgets.QAction(mainWindow)
        self.actionH0_Bandpass.setObjectName("actionH0_Bandpass")
        self.actionAuto = QtWidgets.QAction(mainWindow)
        self.actionAuto.setObjectName("actionAuto")
        self.actionFast_Bandpass = QtWidgets.QAction(mainWindow)
        self.actionFast_Bandpass.setObjectName("actionFast_Bandpass")
        self.actionFaster_Bandpass = QtWidgets.QAction(mainWindow)
        self.actionFaster_Bandpass.setObjectName("actionFaster_Bandpass")
        self.actionLitke = QtWidgets.QAction(mainWindow)
        self.actionLitke.setObjectName("actionLitke")
        self.actionNone = QtWidgets.QAction(mainWindow)
        self.actionNone.setObjectName("actionNone")
        self.actionSpike_threshold = QtWidgets.QAction(mainWindow)
        self.actionSpike_threshold.setObjectName("actionSpike_threshold")
        self.actionTime_window = QtWidgets.QAction(mainWindow)
        self.actionTime_window.setObjectName("actionTime_window")
        self.menuLoad_offline_data.addAction(self.action_npz)
        self.menuLoad_offline_data.addAction(self.action_mat)
        self.menuLoad_offline_data.addAction(self.action_csv)
        self.menuSave_as.addAction(self.action_save_npz)
        self.menuSave_as.addAction(self.action_save_mat)
        self.menuSave_as.addAction(self.action_save_csv)
        self.menuExport_image.addAction(self.actionEntire_window)
        self.menuExport_image.addAction(self.actionWindow_1)
        self.menuExport_image.addAction(self.actionWindow_2)
        self.menuExport_image.addAction(self.actionWindow_3)
        self.menuExport_image.addAction(self.actionWindow_4)
        self.menuFile.addAction(self.actionNew_session)
        self.menuFile.addAction(self.menuLoad_offline_data.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.menuSave_as.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExport_image.menuAction())
        self.menuEdit.addAction(self.actionPreferences)
        self.menuEdit.addAction(self.actionAnalysis_parameters)
        self.menuArray_Map.addAction(self.actionParameter_1)
        self.menuArray_Map.addAction(self.actionParameter_2)
        self.menuArray_Map.addAction(self.actionParameter_3)
        self.menuChannel_Traces.addAction(self.actionParameter_4)
        self.menuChannel_Traces.addAction(self.actionParameter_5)
        self.menuChannel_Traces.addSeparator()
        self.menuChannel_Traces.addAction(self.actionSpike_threshold)
        self.menuChannel_Traces.addAction(self.actionTime_window)
        self.menuSpike_Rate_Plot.addAction(self.actionParameter_6)
        self.menuSpike_Rate_Plot.addAction(self.actionParameter_7)
        self.menuSpike_Rate_Plot.addAction(self.actionParameter)
        self.menuElectrode_Minimap.addAction(self.actionParameter_8)
        self.menuElectrode_Minimap.addAction(self.actionParameter_9)
        self.menuElectrode_Minimap.addAction(self.actionParameter_10)
        self.menuView.addAction(self.menuArray_Map.menuAction())
        self.menuView.addAction(self.menuChannel_Traces.menuAction())
        self.menuView.addAction(self.menuSpike_Rate_Plot.menuAction())
        self.menuView.addAction(self.menuElectrode_Minimap.menuAction())
        self.menuView.addSeparator()
        self.menuTop_left.addAction(self.actionArray_map)
        self.menuTop_left.addAction(self.actionChannel_Traces_2)
        self.menuTop_left.addAction(self.actionSpike_Rate_Plot_2)
        self.menuTop_left.addAction(self.actionElectrode_Minimap)
        self.menuTop_left.addAction(self.actionTrace_Search)
        self.menuTop_right.addAction(self.actionArray_Map_2)
        self.menuTop_right.addAction(self.actionChannel_Traces)
        self.menuTop_right.addAction(self.actionSpike_Rate_Plot)
        self.menuTop_right.addAction(self.actionElectrode_Minimap_2)
        self.menuTop_right.addAction(self.actionTrace_Search_2)
        self.menuBottom_left.addAction(self.actionArray_Map_3)
        self.menuBottom_left.addAction(self.actionChannel_Traces_3)
        self.menuBottom_left.addAction(self.actionSpike_Rate_Plot_3)
        self.menuBottom_left.addAction(self.actionElectrode_Minimap_3)
        self.menuBottom_left.addAction(self.actionTrace_Search_3)
        self.menuBottom_right.addAction(self.actionArray_Map_4)
        self.menuBottom_right.addAction(self.actionChannel_Traces_4)
        self.menuBottom_right.addAction(self.actionSpike_Rate_Plot_4)
        self.menuBottom_right.addAction(self.actionElectrode_Minimap_4)
        self.menuBottom_right.addAction(self.actionTrace_Search_4)
        self.menuWindow.addAction(self.actionChange_layout)
        self.menuWindow.addAction(self.menuTop_left.menuAction())
        self.menuWindow.addAction(self.menuTop_right.menuAction())
        self.menuWindow.addAction(self.menuBottom_left.menuAction())
        self.menuWindow.addAction(self.menuBottom_right.menuAction())
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionToggle_light_dark_mode)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuFilter_design.addAction(self.actionParameter_11)
        self.menuFilter_design.addAction(self.actionParameter_12)
        self.menuFilter_design.addAction(self.actionParameter_13)
        self.menuFilter_design.addAction(self.actionH0_Bandpass)
        self.menuFilter_design.addAction(self.actionAuto)
        self.menuFilter_design.addAction(self.actionFast_Bandpass)
        self.menuFilter_design.addAction(self.actionFaster_Bandpass)
        self.menuFilter_design.addAction(self.actionLitke)
        self.menuFilter_design.addAction(self.actionNone)
        self.menuSettings.addAction(self.menuFilter_design.menuAction())
        self.menuSettings.addAction(self.actionSpike_detection)
        self.menuSettings.addAction(self.actionToggle_profiling)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "DC1 Visualization"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuLoad_offline_data.setTitle(_translate("mainWindow", "Load offline data..."))
        self.menuSave_as.setTitle(_translate("mainWindow", "Save as..."))
        self.menuExport_image.setTitle(_translate("mainWindow", "Export image..."))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuArray_Map.setTitle(_translate("mainWindow", "Array Map"))
        self.menuChannel_Traces.setTitle(_translate("mainWindow", "Channel Traces"))
        self.menuSpike_Rate_Plot.setTitle(_translate("mainWindow", "Spike Rate Plot"))
        self.menuElectrode_Minimap.setTitle(_translate("mainWindow", "Electrode Minimap"))
        self.menuWindow.setTitle(_translate("mainWindow", "Window"))
        self.menuTop_left.setTitle(_translate("mainWindow", "Top left..."))
        self.menuTop_right.setTitle(_translate("mainWindow", "Top right..."))
        self.menuBottom_left.setTitle(_translate("mainWindow", "Bottom left..."))
        self.menuBottom_right.setTitle(_translate("mainWindow", "Bottom right..."))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings"))
        self.menuFilter_design.setTitle(_translate("mainWindow", "Filter"))
        self.actionNew_session.setText(_translate("mainWindow", "New real-time session..."))
        self.actionLoad_real_time_stream.setText(_translate("mainWindow", "Load real-time stream..."))
        self.actionChange_layout.setText(_translate("mainWindow", "Change layout"))
        self.actionDocumentation.setText(_translate("mainWindow", "Documentation"))
        self.actionParameter_1.setText(_translate("mainWindow", "Parameter 1"))
        self.actionParameter_2.setText(_translate("mainWindow", "Parameter 2"))
        self.actionParameter_3.setText(_translate("mainWindow", "Parameter 3"))
        self.actionPreferences.setText(_translate("mainWindow", "Preferences..."))
        self.actionAnalysis_parameters.setText(_translate("mainWindow", "Analysis parameters"))
        self.actionSave.setText(_translate("mainWindow", "Save"))
        self.actionExport_to.setText(_translate("mainWindow", "Export to..."))
        self.actionParameter_4.setText(_translate("mainWindow", "Toggle highlight spikes"))
        self.actionParameter_5.setText(_translate("mainWindow", "Toggle auto axis"))
        self.actionParameter_6.setText(_translate("mainWindow", "Parameter 1"))
        self.actionParameter_7.setText(_translate("mainWindow", "Parameter 2"))
        self.actionParameter.setText(_translate("mainWindow", "Parameter 3"))
        self.actionParameter_8.setText(_translate("mainWindow", "Parameter 1"))
        self.actionParameter_9.setText(_translate("mainWindow", "Parameter 2"))
        self.actionParameter_10.setText(_translate("mainWindow", "Parameter 3"))
        self.actionArray_map.setText(_translate("mainWindow", "Array Map"))
        self.actionArray_Map_2.setText(_translate("mainWindow", "Array Map"))
        self.actionArray_Map_3.setText(_translate("mainWindow", "Array Map"))
        self.actionArray_Map_4.setText(_translate("mainWindow", "Array Map"))
        self.actionChannel_Traces_2.setText(_translate("mainWindow", "Channel Traces"))
        self.actionChannel_Traces_3.setText(_translate("mainWindow", "Channel Traces"))
        self.actionChannel_Traces_4.setText(_translate("mainWindow", "Channel Traces"))
        self.actionSpike_Rate_Plot_2.setText(_translate("mainWindow", "Spike Rate Plot"))
        self.actionElectrode_Minimap.setText(_translate("mainWindow", "Electrode Minimap"))
        self.actionParameter_11.setText(_translate("mainWindow", "Hierlemann"))
        self.actionParameter_12.setText(_translate("mainWindow", "Modified Hierlemann"))
        self.actionParameter_13.setText(_translate("mainWindow", "Highpass"))
        self.actionSpike_detection.setText(_translate("mainWindow", "Spike detection..."))
        self.action_npz.setText(_translate("mainWindow", "Numpy file (.npz)"))
        self.action_mat.setText(_translate("mainWindow", "MATLAB file (.mat)"))
        self.action_save_npz.setText(_translate("mainWindow", "Numpy file (.npz)"))
        self.action_save_mat.setText(_translate("mainWindow", "MATLAB file (.mat)"))
        self.actionChannel_Traces.setText(_translate("mainWindow", "Channel Traces"))
        self.actionSpike_Rate_Plot.setText(_translate("mainWindow", "Spike Rate Plot"))
        self.actionElectrode_Minimap_2.setText(_translate("mainWindow", "Electrode Minimap"))
        self.actionSpike_Rate_Plot_3.setText(_translate("mainWindow", "Spike Rate Plot"))
        self.actionElectrode_Minimap_3.setText(_translate("mainWindow", "Electrode Minimap"))
        self.actionSpike_Rate_Plot_4.setText(_translate("mainWindow", "Spike Rate Plot"))
        self.actionElectrode_Minimap_4.setText(_translate("mainWindow", "Electrode Minimap"))
        self.action_save_csv.setText(_translate("mainWindow", "CSV file (.csv)"))
        self.action_csv.setText(_translate("mainWindow", "CSV file (.csv)"))
        self.actionEntire_window.setText(_translate("mainWindow", "Entire window"))
        self.actionWindow_1.setText(_translate("mainWindow", "Window 1"))
        self.actionWindow_2.setText(_translate("mainWindow", "Window 2"))
        self.actionWindow_3.setText(_translate("mainWindow", "Window 3"))
        self.actionWindow_4.setText(_translate("mainWindow", "Window 4"))
        self.actionTrace_Search.setText(_translate("mainWindow", "Trace Search"))
        self.actionTrace_Search_2.setText(_translate("mainWindow", "Trace Search"))
        self.actionTrace_Search_3.setText(_translate("mainWindow", "Trace Search"))
        self.actionTrace_Search_4.setText(_translate("mainWindow", "Trace Search"))
        self.actionToggle_light_dark_mode.setText(_translate("mainWindow", "Toggle light/dark mode"))
        self.actionToggle_profiling.setText(_translate("mainWindow", "Toggle profiling"))
        self.actionH0_Bandpass.setText(_translate("mainWindow", "h0 Bandpass"))
        self.actionAuto.setText(_translate("mainWindow", "Auto"))
        self.actionFast_Bandpass.setText(_translate("mainWindow", "Fast Bandpass"))
        self.actionFaster_Bandpass.setText(_translate("mainWindow", "Faster Bandpass"))
        self.actionLitke.setText(_translate("mainWindow", "Litke"))
        self.actionNone.setText(_translate("mainWindow", "None"))
        self.actionSpike_threshold.setText(_translate("mainWindow", "Spike threshold..."))
        self.actionTime_window.setText(_translate("mainWindow", "Time window..."))

from pyqtgraph import PlotWidget
